### ISSUE TITLE
Doesn't work on A12L

### ISSUE THREAD

**Issue by k2helix** [NextAlone/InstallerPlus#9]
As the title says, the module does not work on Android 12L, sdk 32. Logs say java.lang.UnsupportedClassVersionError

**Comment by k2helix** [comment]
So has A12L support been implemented or just another log to be shown instead?

**Comment by k2helix** [comment]
It indeed works now, thanks! Using default user language would be nice too, as the docs are also in English but the version string is added in Chinese.
Everything else is fine, thanks!

**Comment by k2helix** [comment]
Hmmm maybe it is because the activity it is pointing at is the installer one and it does not have this app's resources? I'm not an Android developer but that's what comes to my mind

**Comment by huajijam** [comment]
> > > Hmmm maybe it is because the activity it is pointing at is the installer one and it does not have this app's resources? I'm not an Android developer but that's what comes to my mind
> > 
> > use latest release and try now
> 
> Package installer crashes with the following error:
> 
> ```
> FATAL EXCEPTION: main
> Process: com.android.packageinstaller, PID: 18720
> android.content.res.Resources$NotFoundException: String resource ID #0x75060001
> 	at android.content.res.Resources.getText(Resources.java:444)
> 	at android.content.res.Resources.getString(Resources.java:537)
> 	at android.content.Context.getString(Context.java:705)
> 	at ltd.nextalone.pkginstallerplus.sdk31.PackageInstallerActivityHook31$initOnce$1$1$1.run(SourceFile:8)
> 	at android.os.Handler.handleCallback(Handler.java:938)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loopOnce(Looper.java:201)
> 	at android.os.Looper.loop(Looper.java:288)
> 	at android.app.ActivityThread.main(ActivityThread.java:7870)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
> ```

should work with latest release now,tested on AVD

**Comment by k2helix** [comment]
Yup, it works fine now. Thank you a lot!
